[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "geopandas",
    "imageio",
    "pandas",
    "pathlib",
    "matplotlib",
    "numpy",
    "laspy",
    "rasterio",
    "folium",
    "shapely",
    "geoplot"
]
build-backend = "setuptools.build_meta"